# Generated by Django 4.2.1 on 2023-05-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_cuidador_cuidadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidadores',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='cuidadores',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='cuidadores',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='cuidadores',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cuidadores',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='cuidadores',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='cuidadores',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='cuidadores',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cuidadores',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Edad'),
        ),
        migrations.AddField(
            model_name='cuidadores',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='cuidadores',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='cuidadores',
            name='image',
            field=models.ImageField(null=True, upload_to='caretaker_images', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='cuidadores',
            name='last_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='cuidadores',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='cuidadores',
            name='password',
            field=models.CharField(max_length=100, null=True, verbose_name='Contraseña'),
        ),
        migrations.AddField(
            model_name='cuidadores',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Teléfono'),
        ),
    ]
