# Generated by Django 4.2.1 on 2023-05-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cuidadores_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidadores',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
