# Generated by Django 4.2.1 on 2023-07-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_cuidadores_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("IdProducto", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombreProducto",
                    models.CharField(max_length=200, verbose_name="NombreProducto"),
                ),
                ("precioProducto", models.IntegerField(verbose_name="PrecioProducto")),
                ("stockProducto", models.IntegerField(verbose_name="StockProducto")),
            ],
        ),
    ]
