# Generated by Django 4.2.1 on 2023-07-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_producto"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(null=True, upload_to="", verbose_name="Imagen"),
        ),
    ]
